#!/usr/bin/env python3

import string
import time
import json
import requests

API_TOKEN= {
    'Authorization': 'lz2lkW8cmEGSIUhC0JnIkouhhiPYB8WM',
}

get_domain_list = requests.get('https://api.ukfast.io/safedns/v1/zones', headers=API_TOKEN)

api_full_response = json.dumps(get_domain_list.json())
api_full_response_dict = json.loads(api_full_response)

print (api_full_response_dict['data'])

print ("-----------------")
test = json.loads(json.dumps(get_domain_list.json()))
print (test)

# #########################################
# NOTES
#
## List Zones
#curl -sX GET https://api.ukfast.io/safedns/v1/zones -H "Authorization: $api_token" | grep -Po '"name":.*?[^\]",' | cut -f4 -d"
